# This is the default configuration for a resetti profile.
# You can delete or ignore any sections which are not applicable.

[general]
# The type of reset style to use.
# Available options:
# - standard    Traditional single/multi-instance resetting for random seeds.
# - wall        Wall-style resetting for random seeds.
# - setseed     Set-seed resetter for good spawns, like spawn-juicer.
type = "standard"

# Whether or not to count the amount of resets performed.
count_resets = false

# The file to use for counting resets. This can be left blank
# if count_resets is disabled.
resets_file = ""

# Process affinity settings.
[affinity]
# Whether or not to enable affinity management.
enabled = false

# The affinity setting to use. Available options:
# - sequence    Set instances to run on every CPU       (0,   1,   2,   ..).
# - alternate   Set instances to run on every other CPU (0,   2,   4,   ..).
# - double      Set instances to run on 2 CPUs each     (0-1, 2-3, 4-5, ..).
# - advanced    Set instances to run on certain CPUs based on their state.
#               Only works with wall.
#
# Considerations:
# - Unless you are using advanced, you can disregard the rest of the affinity
#   options.
# - If you are using advanced, the total number of allocated CPUs must be less
#   than or equal to your processor's thread count. The values provided below
#   are an example for a 6c/12t CPU.
# - Advanced mode is likely not necessary unless you are running more instances
#   than you have CPU cores.
mode = "double"

# The number of CPUs to allocate to idle instances.
cpus_idle = 1

# The number of CPUs to allocate to locked resetting instances and non-previewing instances.
cpus_genfast = 4

# The number of CPUs to allocate to unlocked resetting instances on the preview.
cpus_genslow = 5

# The number of CPUs to dedicate to the active (played) instance.
cpus_active = 2

# Which state the active CPUs should be reallocated to when no instance is
# being played. Available options:
# - none        Do not reallocate the CPUs dedicated to the active instance.
# - genfast     Dedicate the unused active CPUs to the high-priority instances.
# - genslow     Dedicate the unused active CPUs to the low-priority instances.
reallocate = "genfast"

# Here, you can set various commands or shell scripts to run when certain
# events occur. Anything left blank will be ignored.
[hooks]
# The command/script to run when a reset from the wall occurs.
wall_reset = ""

# The command/script to run when a reset occurs.
reset = ""

# The command/script to run when an instance is locked on the wall.
lock = ""

# The command/script to run when an instance is unlocked on the wall.
unlock = ""

[obs]
# Whether or not to enable OBS websocket support. This is *required* for wall and setseed.
enabled = false

# The port to connect to OBS websocket on.
port = 4440

# The password to use when connecting. This can be left blank if you have
# authentication disabled in OBS websocket.
password = ""

[reset]
# The amount of milliseconds to wait before pausing and fullscreening instances.
delay = 50

# Whether or not to automatically unpause the game when an instance is focused.
unpause_on_focus = true

# - You can ignore any keybindings here which do not apply to your reset style.
# - Alphanumerical and Fn keys (1-12) are supported.
# - You can supply modifiers (Shift, Control, Alt) as well.
# - The values written are not case sensitive (e.g. `a` and `A` are equivalent,
#   specify the `Shift` modifier.)
# - There is no distinction between the left and right modifier keys.
# - For the wall keys, you may only specify modifiers. For example, if you specify
#   Shift as your wall instance reset keybind, pressing Shift-1 will reset the
#   first instance (if you have mouse support enabled, shift clicking will work
#   as well.) You can leave the keybind blank for no modifier.
# - Do not have multiple identical keybinds.
#
#   Examples:
#               `A` => The A key.
#               `a` => The A key.
#         `Shift-A` => The A key, only when Shift is held.
#  `Ctrl-Shift-F12` => The F12 key with Control and Shift held.
#
[keybinds]
# Pressing this will focus the current instance.
# If you on the wall, pressing this will send you back to the OBS projector.
focus = "Ctrl-Shift-F"

# Pressing this will reset the current instance.
# If you are on the wall, pressing this will reset all instances.
reset = "Ctrl-Shift-R"

# Pressing this will reset the selected instance.
wall_reset = ""

# Pressing this will play the selected instance and reset all other instances.
wall_reset_others = "Ctrl-Shift"

# Pressing this will play the selected instance.
wall_play = "Shift"

# Pressing this will lock the selected instance.
wall_lock = "Ctrl"

[wall]
# Whether or not to stretch windows while on the wall for better visibility.
# Works with or without fullscreen.
stretch_windows = false

# The width to stretch windows to on the wall scene.
stretch_width = 1600

# The height to stretch windows to on the wall scene.
stretch_height = 300

# The width to unstretch windows to when being played.
unstretch_width = 1920

# The height to unstretch windows to when being played.
unstretch_height = 1080

# Whether or not to enable mouse support on the wall. Enabling this will allow
# you to click on instances to perform various actions instead of having to use
# the number keys. Note that enabling this does not disable the number keys.
use_mouse = false

# If enabled, resetting from within an instance will switch to the first locked
# instance (if any) instead of going back to the wall.
goto_locked = false

# You can delete this section or leave it as is if you are not using the
# set-seed resetter.
[setseed]
# The seed to use.
seed = "my_seed"

# The desired spawn X and Z coordinates.
spawn_x = 123.0
spawn_z = 456.0

# The radius around the given X/Z coordinates which is considered "good."
radius = 5.0
