obs:
  enabled: false
  port: 4440
  password: password
keys:
  reset: 0;0
  focus: 0;0
wall:
  mod-reset: 0
  mod-reset-others: 0
  mod-play: 0
reset:
  mc:
    fov: 70
    rd: 16
    sensitivity: 100
  set-settings: false
  delay: 50
