name: Create release build

on:
  push:
    tags:
      - v*

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch history to add correct version in Makefile
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.4"

      - name: Build and package resetti
        run: make deb

      - name: Get release info
        id: tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/resetti.deb,out/resetti,out/bench"
          draft: true
          name: ${{ steps.tag.outputs.tag }}
          tag: ${{ steps.tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
